### ISSUE TITLE
node scripts/install.js stops npm install

### ISSUE THREAD

**Issue by MarcoHengstenberg** [jakearchibald/wittr#3]
Hello there,

while following the course on Udacity I ran into a problem with npm. I ran `npm install` inside the /wittr folder on my local machine. It stopped running at the following line of output:

`> node scripts/install.js`

Now, after stopping the script with _ctrl + c_ on `npm run serve` I got the following output:

```
> wittr@1.0.0 serve /Users/nice2meatu/Sites/Git/wittr
> gulp serve

(node:34185) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[11:33:06] Using gulpfile ~/Sites/Git/wittr/gulpfile.js
[11:33:06] Starting 'serve'...
[11:33:06] Starting 'clean'...
[11:33:06] Finished 'clean' after 6.13 ms
[11:33:06] Starting 'css'...
[11:33:06] 'css' errored after 19 ms
[11:33:06] Error: dlopen(/Users/nice2meatu/Sites/Git/wittr/node_modules/node-sass/vendor/darwin-x64-48/binding.node, 1): no suitable image found.  Did find:
	/Users/nice2meatu/Sites/Git/wittr/node_modules/node-sass/vendor/darwin-x64-48/binding.node: truncated mach-o error: segment __TEXT extends to 1212416 which is past end of file 34352
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/nice2meatu/Sites/Git/wittr/node_modules/node-sass/lib/index.js:24:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
[11:33:06] 'serve' errored after 32 ms
[11:33:06] Error in plugin 'run-sequence(css)'
Message:
    css catch

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! wittr@1.0.0 serve: `gulp serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wittr@1.0.0 serve script 'gulp serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wittr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wittr
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wittr
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nice2meatu/Sites/Git/wittr/npm-debug.log
```

Ideas? 😃

**Comment by jasonloeve** [comment]
Did you find out what is causing this, been trying to figure it out for two days, node scripts/install.js hang for over night before i stopped the command .... cant get passed this point of the install

**Comment by jakearchibald** [comment]
Will look into this - sorry for the delay

**Comment by jakearchibald** [comment]
Hmm, just tested this on git bash & windows bash with node 6.2.1 and 6.3.1 - can't recreate the problem.

Try installing again from fresh?

```sh
rm -rf node_modules
npm install
```

**Comment by MarcoHengstenberg** [comment]
Hello Jake,

I have been on vacation for a week. I'll try and install the whole thing from scratch.
Hope it will be gone already. 😃

**Comment by MarcoHengstenberg** [comment]
Okay, so the offender was:

```bash
> node-sass@3.8.0 install ../wittr/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at ../wittr/node_modules/node-sass/vendor/darwin-x64-48/binding.node
```

Whatever caused the error (three times in a row, then I gave up and created this issue) seems to be resolved. 👍
