### ISSUE TITLE
[Bug] npm run serve produces errors and doesnt start the servers

### ISSUE THREAD

**Issue by jtan21at** [jakearchibald/wittr#44]
npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "serve"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! wittr@1.0.0 serve: `gulp serve`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the wittr@1.0.0 serve script 'gulp serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wittr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wittr
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wittr
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jw/wittr/npm-debug.log

**Comment by bvasilop** [comment]
Did you try cd wittr before npm install ?

**Comment by ghost** [comment]
It looks like maybe the packages were not npm installed

**Comment by Nickbahson** [comment]
Anyone got it to work..still stuck
that helped
https://nodejs.org/en/download/package-manager/

**Comment by GenieCloud** [comment]
I keep getting this error message when I run 'npm run serve' in the wittr directory. Can anyone help me with this please? 

Error: listen EPERM offlinefirst.sock
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1237:19)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1376:5)
    at Server._listen (/mnt/c/Users/jmjon/Desktop/wittr/build/server/Server.js:329:25)
    at Server.setConnectionType (/mnt/c/Users/jmjon/Desktop/wittr/build/server/Server.js:355:14)
    at Object.<anonymous> (/mnt/c/Users/jmjon/Desktop/wittr/build/server/index.js:27:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
