### ISSUE TITLE
Error: Cannot find module 'deck'

### ISSUE THREAD

**Issue by ghost** [jakearchibald/wittr#54]
After pulling the repo from git and doing an npm install with no errors, when trying to run the application I get the following error:

```
> wittr@1.0.0 serve /Users/kbj110/Desktop/wittr
> gulp serve

[08:52:23] Using gulpfile ~/Desktop/wittr/gulpfile.js
[08:52:23] Starting 'serve'...
[08:52:23] Starting 'clean'...
[08:52:23] Finished 'clean' after 34 ms
[08:52:23] Starting 'css'...
[08:52:23] Starting 'js:browser'...
[08:52:23] Starting 'templates:server'...
[08:52:23] Starting 'js:server'...
[08:52:23] Starting 'copy'...
[08:52:25] 67987 bytes written (1.54 seconds)
[08:52:25] 2700 bytes written (1.63 seconds)
[08:52:25] Finished 'css' after 1.91 s
[08:52:25] Finished 'templates:server' after 1.82 s
[08:52:25] 27444 bytes written (2.17 seconds)
[08:52:25] Finished 'js:server' after 2.22 s
[08:52:25] 25441 bytes written (2.22 seconds)
[08:52:26] 142120 bytes written (2.40 seconds)
[08:52:26] 91694 bytes written (2.43 seconds)
[08:52:26] 207007 bytes written (2.61 seconds)
[08:52:26] Finished 'js:browser' after 2.71 s
[08:52:26] Finished 'copy' after 2.64 s
[08:52:26] Starting 'server'...
[08:52:26] Finished 'server' after 34 ms
[08:52:26] Starting 'watch'...
[08:52:26] Finished 'watch' after 43 ms
[08:52:26] Finished 'serve' after 2.91 s
[08:52:26] Development server has error.
module.js:471
    throw err;
    ^

Error: Cannot find module 'deck'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kbj110/Desktop/wittr/node_modules/markov/index.js:2:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by ghost** [comment]
All of a sudden works. Not sure what did the trick!
