### ISSUE TITLE
Error on npm run serve node v4.5.0 and npm 2.15.9 

### ISSUE THREAD

**Issue by GenieCloud** [jakearchibald/wittr#59]
Error: listen EPERM offlinefirst.sock
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1237:19)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1376:5)
    at Server._listen (/mnt/c/Users/jmjon/Desktop/wittr/build/server/Server.js:329:25)
    at Server.setConnectionType (/mnt/c/Users/jmjon/Desktop/wittr/build/server/Server.js:355:14)
    at Object.<anonymous> (/mnt/c/Users/jmjon/Desktop/wittr/build/server/index.js:27:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

This is the error I receive after run 'npm install' and 'npm run serve'. Any assistance would be greatly appreciate. Thank you :)

**Comment by GenieCloud** [comment]
Solved by re-running npm install with the suggested node version 4.5.0 and npm version 2.15.9 also delete the node modules folder in the wittr first in order to ensure a proper build.
