### ISSUE TITLE
npm ERR! code EACCES,! errno EACCES, FetchError: request to https://registry.npmjs.org/babel-eslint failed, reason: connect EACCES 104.18.94.96:443

### ISSUE THREAD

**Issue by SirG97** [jakearchibald/wittr#69]
I have gone through this installation before and everything worked out fine, after formatting my laptop, and installing a fresh copy of node, it refused to work. Anybody with any ideas on how to go about this..
npm ERR! code EACCES
npm ERR! errno EACCES
npm ERR! FetchError: request to https://registry.npmjs.org/babel-eslint failed, reason: connect EACCES 104.18.94.96:443
npm ERR!     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at ClientRequest.emit (events.js:211:7)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:387:9)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at TLSSocket.emit (events.js:211:7)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR!  { FetchError: request to https://registry.npmjs.org/babel-eslint failed, reason: connect EACCES 104.18.94.96:443
npm ERR!     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at ClientRequest.emit (events.js:211:7)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:387:9)
npm ERR!     at emitOne (events.js:116:13)
npm ERR!     at TLSSocket.emit (events.js:211:7)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR!     at _combinedTickCallback (internal/process/next_tick.js:138:11)
npm ERR!     at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR!   message: 'request to https://registry.npmjs.org/babel-eslint failed, reason: connect EACCES 104.18.94.96:443',
npm ERR!   type: 'system',
npm ERR!   errno: 'EACCES',
npm ERR!   code: 'EACCES',
npm ERR!   stack: 'FetchError: request to https://registry.npmjs.org/babel-eslint failed, reason: connect EACCES 104.18.94.96:443\n    at ClientRequest.req.on.err (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\pacote\\node_modules\\make-fetch-happen\\node_modules\\node-fetch-npm\\src\\index.js:68:14)\n    at emitOne (events.js:116:13)\n    at ClientRequest.emit (events.js:211:7)\n    at TLSSocket.socketErrorListener (_http_client.js:387:9)\n    at emitOne (events.js:116:13)\n    at TLSSocket.emit (events.js:211:7)\n    at emitErrorNT (internal/streams/destroy.js:64:8)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)',
npm ERR!   parent: 'wittr' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\School\AppData\Roaming\npm-cache\_logs\2018-05-27T13_27_17_251Z-debug.log

**Comment by gkalarus** [comment]
Have you managed to deal with this problem?

**Comment by tiffanik97** [comment]
@SirG97 have you manage to fix it because I am facing the same issue. 


C:\Users\natal>npm install -g npm@latest
npm ERR! code EACCES
npm ERR! errno EACCES
npm ERR! FetchError: request to https://registry.npmjs.org/npm failed, reason: connect EACCES 104.16.22.35:443
npm ERR!     at ClientRequest.<anonymous> (C:\Users\natal\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:210:5)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:406:9)
npm ERR!     at TLSSocket.emit (events.js:210:5)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:92:8)
npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR!  FetchError: request to https://registry.npmjs.org/npm failed, reason: connect EACCES 104.16.22.35:443
npm ERR!     at ClientRequest.<anonymous> (C:\Users\natal\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:210:5)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:406:9)
npm ERR!     at TLSSocket.emit (events.js:210:5)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:92:8)
npm ERR!     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
npm ERR!   message: 'request to https://registry.npmjs.org/npm failed, reason: connect EACCES 104.16.22.35:443',
npm ERR!   type: 'system',
npm ERR!   errno: 'EACCES',
npm ERR!   code: 'EACCES',
npm ERR!   stack: 'FetchError: request to https://registry.npmjs.org/npm failed, reason: connect EACCES 104.16.22.35:443\n' +
npm ERR!     '    at ClientRequest.<anonymous> (C:\\Users\\natal\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-fetch-npm\\src\\index.js:68:14)\n' +
npm ERR!     '    at ClientRequest.emit (events.js:210:5)\n' +
npm ERR!     '    at TLSSocket.socketErrorListener (_http_client.js:406:9)\n' +
npm ERR!     '    at TLSSocket.emit (events.js:210:5)\n' +
npm ERR!     '    at emitErrorNT (internal/streams/destroy.js:92:8)\n' +
npm ERR!     '    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)\n' +
npm ERR!     '    at processTicksAndRejections (internal/process/task_queues.js:80:21)'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\natal\AppData\Roaming\npm-cache\_logs\2019-11-03T06_39_12_017Z-debug.log

**Comment by tiffanik97** [comment]
@SirG97 Please help ASAP. Thank you.

**Comment by raedabusanad** [comment]
I still have this issue..the only thing i noticed it behaves differently based on connected internet access points. 
e.g. it did work when connecting through phone's hotspot, but did NOT work with home wifi.
Also it did work with company visitor wifi, but not private access point

**Comment by Ganesh8894** [comment]
I'm facing the same issue , can anyone help please 
reason: connect EACCES 104.16.16.35:443

**Comment by Ganesh8894** [comment]
I'm getting the same error ,Any help would be appreciated .thanks in advance.


PS C:\Users\Ganesh\CypressPractice> npm install cypress --save-dev
npm ERR! code EACCES 
npm ERR! errno EACCES
npm ERR! FetchError: request to https://registry.npmjs.org/cypress failed, reason: connect EACCES 104.16.16.35:443
npm ERR!     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:376:20)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:475:9)
npm ERR!     at TLSSocket.emit (events.js:376:20)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:106:8)
npm ERR!     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR!  FetchError: request to https://registry.npmjs.org/cypress failed, reason: connect EACCES 104.16.16.35:443
npm ERR!     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:376:20)
npm ERR!     at TLSSocket.socketErrorListener (_http_client.js:475:9)
npm ERR!     at TLSSocket.emit (events.js:376:20)
npm ERR!     at emitErrorNT (internal/streams/destroy.js:106:8)
npm ERR!     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
npm ERR!   type: 'system',
npm ERR!   errno: 'EACCES',
npm ERR!   code: 'EACCES'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ganesh\AppData\Roaming\npm-cache\_logs\2021-06-09T15_57_13_670Z-debug.log
PS C:\Users\Ganesh\CypressPractice>

**Comment by theodore360** [comment]
C:\Users\**username**>npm install -g cordova
npm ERR! code EACCES
npm ERR! errno EACCES
npm ERR! FetchError: request to https://registry.npmjs.org/cordova failed, reason: connect EACCES **my_proxy_ip**:**my_port**
npm ERR!     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:375:28)
npm ERR!     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:101:9)
npm ERR!     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:123:5)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR!  FetchError: request to https://registry.npmjs.org/cordova failed, reason: connect EACCES **my_proxy_ip**:**my_port**
npm ERR!     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
npm ERR!     at ClientRequest.emit (events.js:375:28)
npm ERR!     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:101:9)
npm ERR!     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:123:5)
npm ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
npm ERR!   type: 'system',
npm ERR!   errno: 'EACCES',
npm ERR!   code: 'EACCES'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\**username**\AppData\Roaming\npm-cache\_logs\2021-07-21T00_35_31_354Z-debug.log

**Comment by ScarlettV-dev** [comment]
I'm having the same issue, if you guys please have the solution write me ASAP

**Comment by umangsahu** [comment]
code EACCES
npm ERR! syscall connect
npm ERR! errno EACCES
npm ERR! FetchError: request to http://registry.npmjs.org/-/v1/login failed, reason: connect EACCES 104.16.16.35:80
npm ERR!     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:527:28)
npm ERR!     at Socket.socketErrorListener (node:_http_client:454:9)
npm ERR!     at Socket.emit (node:events:539:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR!  FetchError: request to http://registry.npmjs.org/-/v1/login failed, reason: connect EACCES 104.16.16.35:80
npm ERR!     at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
npm ERR!     at ClientRequest.emit (node:events:527:28)
npm ERR!     at Socket.socketErrorListener (node:_http_client:454:9)
npm ERR!     at Socket.emit (node:events:539:35)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
npm ERR!   code: 'EACCES',
npm ERR!   errno: 'EACCES',
npm ERR!   syscall: 'connect',
npm ERR!   address: '104.16.16.35',
npm ERR!   port: 80,
npm ERR!   type: 'system'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

**Comment by umangsahu** [comment]
please if anybody help me
