### ISSUE TITLE
Error on npm run serve

### ISSUE THREAD

**Issue by rahul2983** [jakearchibald/wittr#74]
After I install (node v4.5.0 and npm v2.15.9) and execute `npm run serve` I get the following error.

```
[16:56:23] Development server has error.
module.js:327
    throw err;
    ^

Error: Cannot find module 'deck'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/psj589/wittr/node_modules/markov/index.js:2:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

Can you please help me out here? I didn't receive any errors or warnings after `npm install`

**Comment by rahul2983** [comment]
I have also tried with node v4.2.1 but with the same outcome.

**Comment by robertjallen** [comment]
I might be because of an internet connection issue? I don't know, but I noticed that if I get alot of errors installing/ building an app, sometimes if I just delete it and do it again it works with no errors. Iv'e learned to compare class build instructions with READ.ME build and try any differences, then delete it and try it again. I don't know why but almost every time iv'e had build issues all I needed to do was delete it and do it again.
